site_name: DicasDeEstagio - G5
#site_author: Mateus Villela
site_description: Site voltado para a documentação do Grupo 5 de Arquitetura e Desenvolvimento de Software - 2025.2

theme:
  name: material

  palette:
    
scheme: default
    primary: "#1A2B45"   # Azul escuro 
    accent: "#00A86B"    # Verde 
    auxiliary: "#36A9E1" # Azul claro 
    toggle:
      icon: material/weather-night
      name: Modo escuro

    
scheme: slate
    primary: "#1A2B45"   # Azul escuro
    accent: "#00A86B"    # Verde
    auxiliary: "#36A9E1" # Azul claro
    toggle:
      icon: material/weather-sunny
      name: Modo claro

nav:
  
Início: index.md
teste: docs/teste.md

markdown_extensions:
  
pymdownx.details
tables
attr_list
md_in_html
pymdownx.blocks.caption
pymdownx.details
pymdownx.superfences

  
pymdownx.arithmatex:
    generic: true

plugins:
  
search
mermaid2
mkdocs-pdf

extra_css:
  
assets/css/custom.css

extra_javascript:
  
https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
